#!/bin/bash

while getopts "h:s:" o; do
	case "${o}" in
		h)
			hostfile=${OPTARG}
			;;
		s)
			scriptfile=${OPTARG}
			;;
	esac
done

while read hostline; do
	echo "`tput setaf 2`[${hostline}]`tput sgr0`"
	ssh ${hostline} 'bash -s' < ${scriptfile}
done < "${hostfile}"
